// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Oms4gTfMQVLLvJbvv8vCLIqQLd787w8',
    appId: '1:834130946589:web:fcb15806ffb2a54aa8b4f4',
    messagingSenderId: '834130946589',
    projectId: 'learning-management-syst-b774b',
    authDomain: 'learning-management-syst-b774b.firebaseapp.com',
    storageBucket: 'learning-management-syst-b774b.appspot.com',
    measurementId: 'G-9QNRJC40S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97MZ980hXyCLUH9YRQqlRQ424t6sQcWw',
    appId: '1:834130946589:android:fc4d7dc3d280cca9a8b4f4',
    messagingSenderId: '834130946589',
    projectId: 'learning-management-syst-b774b',
    storageBucket: 'learning-management-syst-b774b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzju98JO_lC4W9HyQwyE3Fd4uz-c3QLug',
    appId: '1:834130946589:ios:8967421e7b2fafdca8b4f4',
    messagingSenderId: '834130946589',
    projectId: 'learning-management-syst-b774b',
    storageBucket: 'learning-management-syst-b774b.appspot.com',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzju98JO_lC4W9HyQwyE3Fd4uz-c3QLug',
    appId: '1:834130946589:ios:b9853b405d716088a8b4f4',
    messagingSenderId: '834130946589',
    projectId: 'learning-management-syst-b774b',
    storageBucket: 'learning-management-syst-b774b.appspot.com',
    iosBundleId: 'com.example.agriconnect.RunnerTests',
  );
}
