// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLd-aAGs5Bms_i2vYqkk28UoY3H8lNCmM',
    appId: '1:588083323518:web:a5f39f5fc481bba19aee2f',
    messagingSenderId: '588083323518',
    projectId: 'agriculture-lms-ecc73',
    authDomain: 'agriculture-lms-ecc73.firebaseapp.com',
    databaseURL: 'https://agriculture-lms-ecc73-default-rtdb.firebaseio.com',
    storageBucket: 'agriculture-lms-ecc73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbm5LntNivRj7ItuErxxP8docE-tI4Is',
    appId: '1:588083323518:android:afd840227f5e69af9aee2f',
    messagingSenderId: '588083323518',
    projectId: 'agriculture-lms-ecc73',
    databaseURL: 'https://agriculture-lms-ecc73-default-rtdb.firebaseio.com',
    storageBucket: 'agriculture-lms-ecc73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzdpwk6yxHpe3Yqe8PKEP6StOBogn2GKw',
    appId: '1:588083323518:ios:040f2ab635d3c5579aee2f',
    messagingSenderId: '588083323518',
    projectId: 'agriculture-lms-ecc73',
    databaseURL: 'https://agriculture-lms-ecc73-default-rtdb.firebaseio.com',
    storageBucket: 'agriculture-lms-ecc73.appspot.com',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzdpwk6yxHpe3Yqe8PKEP6StOBogn2GKw',
    appId: '1:588083323518:ios:cbc8b9070e42b4699aee2f',
    messagingSenderId: '588083323518',
    projectId: 'agriculture-lms-ecc73',
    databaseURL: 'https://agriculture-lms-ecc73-default-rtdb.firebaseio.com',
    storageBucket: 'agriculture-lms-ecc73.appspot.com',
    iosBundleId: 'com.example.agriconnect.RunnerTests',
  );
}
